### ISSUE TITLE
there is no package called 'mlr3spatiotempcv'

### ISSUE THREAD

**Issue by Nowosad** [geocompx/solutions#2]
https://github.com/geocompr/solutions/actions/runs/3379807347/jobs/5611845955#step:4:468

Strangely, it seems that {geocompkg} does not have {mlr3spatiotempcv} included, even though it is in https://github.com/geocompr/geocompkg/blob/master/DESCRIPTION and we are using the geocompr/geocompr:suggests docker image (https://github.com/geocompr/solutions/blob/e63cbd0edc70a1db4fa0049c06f65ff05a8d4593/.github/workflows/main.yaml#L12). 

Any ideas @Robinlovelace ?

**Comment by Robinlovelace** [comment]
Seems it's been archived: https://cran.r-project.org/web/packages/mlr3spatiotempcv/index.html

**Comment by Robinlovelace** [comment]
But yeah I see it's in the remotes: https://github.com/geocompr/geocompkg/blob/d75e4a586eeac6cd368045b7d2fee822c4a2920b/DESCRIPTION#L113

**Comment by Robinlovelace** [comment]
So no idea what's going on here...

**Comment by Robinlovelace** [comment]
FYI I have noticed issues with actions recently some of them quite confusing: it seems that packages in Remotes are not always installed.

**Comment by Robinlovelace** [comment]
Removing me from the Assignees. I would happily be assigned if I had agreed to work on it and if I knew how. Do you have any ideas @nowosad? May just be a self fixing issue related to upstream changes, e.g. in r-lib/actions and associated packages.

**Comment by Nowosad** [comment]
There is a part of the docker image creation code -- https://github.com/geocompr/docker/blob/c122a67d8599c9a0f45cd71e9ae47205f61bcce4/suggests/Dockerfile#L2.

When I run it locally, it installs {mlr3spatiotempcv}. Maybe it is just an issue with the image build on GHA -- https://github.com/geocompr/docker/actions/runs/3383962763/jobs/5620374176?

**Comment by Robinlovelace** [comment]
Could be an issue with the GHA build, I think that's likely.

**Comment by Nowosad** [comment]
Ok, I think I understand the main issue (but do not know how to fix it yet):

1. We install the dependencies inside using dockerfile (https://github.com/geocompr/docker/blob/c122a67d8599c9a0f45cd71e9ae47205f61bcce4/suggests/Dockerfile#L2)
2. It is done inside of the docker/build-push-action (https://github.com/geocompr/docker/blob/72aa97e472f3c67123bc6c773eab980e0b4f5fbb/.github/workflows/suggests.yml#L55)
3. The problem is that installing several GitHub R packages we are exceeding the API rate limit (https://github.com/geocompr/docker/actions/runs/3342699887/jobs/5535187449#step:8:875)
4. The fix should be related to increasing our GitHub API rate limit with a GitHub Personal Access Token; however, this token must be provided directly to the docker/build-push-action inside our GitHub Action (and not in our GitHub Action itself).

**Comment by Robinlovelace** [comment]
That is a great diagnosis of the issue. Environments is my first thought... Or could we get the packages from another source, e.g. R Universe?

**Comment by Nowosad** [comment]
I am currently trying the approach described in https://github.com/docker/build-push-action/blob/master/docs/advanced/secrets.md -- by sending GITHUB_PAT from GitHub Actions to docker/build-push-action to our dockerfile.

**Comment by Nowosad** [comment]
It took me half a day, but it works now -- https://github.com/geocompr/docker/actions/runs/3385623405. 

Solution: 

1. Add a secret at the bottom of the GHA file -- https://github.com/geocompr/docker/blob/master/.github/workflows/suggests.yml
2. Copy the secret into the .Renviron file in Dockerfile (see lines 2 and 3 at https://github.com/geocompr/docker/blob/master/suggests/Dockerfile)

Now, I can pretend to be a hacker for the rest of the day;)

**Comment by Robinlovelace** [comment]
:tada:

**Comment by jannes-m** [comment]
I am impressed, this is a great hacky-geeky solution 👍

**Comment by Nowosad** [comment]
Thank you, @jannes-m
